### PR TITLE
New section documentation on how to perform local PubSub testing

### LINKED ISSUE #37: Documentation: Unclear how to use events signature-type and test pubsub
Hi,
I was able to setup and do local testing using http signature. However my goal is to do local development on a cloud function that consumes PubSub. What is the best development workflow for this?

I was thinking I may need to set signature-type to event, and somehow pass in a mock pubsub event object, how the current documentation doesn't give me many clues. Could someone point me the way?

Thanks!

### PR DESCRIPTION
**Pull request by betacar**
Fixes #37, and pick ups on #40.

### CODE REVIEW

**Comment by betacar** [comment]
@googlebot I signed it!

**Comment by betacar** [comment]
@grant Done!

**Comment by grant** [comment]
Thank you @betacar!

**Comment by betacar** [comment]
Always happy to halp, @grant!

**Pull request merged**
