### PR TITLE
feat: integrate cloudevents module

### PR DESCRIPTION
**Pull request by grant**
Integrates the CloudEvents SDK for the Node Functions Framework. Does not change functionality.

- Adds `cloudevents` module
- Removes internal interfaces
- Removes binary CloudEvent support for `event` signature. (This signature should not receive or support CloudEvents)
- Updates tests

## Potential Improvements

- Filed bug with CE TS interface: https://github.com/cloudevents/sdk-javascript/issues/294
- Not sure the best way to figure out if a HTTP request is a CE: https://github.com/cloudevents/sdk-javascript/issues/295

## Production Impact

Should not have impact on GCF invoker as:

- We don't currently use `wrapCloudEventFunction` in GCF
- We don't see `isBinaryCloudEvent` resolving to `true` in `wrapEventFunction`
- `cloudevents` bundle size is reasonable at <200kB: https://bundlephobia.com/result?p=cloudevents@3.0.1

CC: @lance @grayside

### CODE REVIEW

**Comment by grant** [comment]
There might be some issues to address before landing this.

Current errors:

```
 tsc -p .

node_modules/cloudevents/dist/event/cloudevent.d.ts:15:5 - error TS1127: Invalid character.

15     #private;
       

node_modules/cloudevents/dist/event/cloudevent.d.ts:15:6 - error TS7008: Member 'private' implicitly has an 'any' type.

15     #private;
        ~~~~~~~

node_modules/cloudevents/dist/transport/index.d.ts:3:10 - error TS1005: 'from' expected.

3 export * as http from "./http/headers";
           ~~

node_modules/cloudevents/dist/transport/index.d.ts:3:10 - error TS1141: String literal expected.

3 export * as http from "./http/headers";
           ~~

node_modules/cloudevents/dist/transport/index.d.ts:3:13 - error TS1005: ';' expected.

3 export * as http from "./http/headers";
              ~~~~

node_modules/cloudevents/dist/transport/index.d.ts:3:13 - error TS2304: Cannot find name 'http'.

3 export * as http from "./http/headers";
              ~~~~

node_modules/cloudevents/dist/transport/index.d.ts:3:18 - error TS1005: ';' expected.

3 export * as http from "./http/headers";
                   ~~~~

node_modules/cloudevents/dist/transport/index.d.ts:3:18 - error TS2304: Cannot find name 'from'.

3 export * as http from "./http/headers";
                   ~~~~

node_modules/cloudevents/dist/transport/index.d.ts:3:23 - error TS1005: ';' expected.

3 export * as http from "./http/headers";         
```

https://github.com/cloudevents/sdk-javascript/issues/272

**Comment by lance** [comment]
@grant consider upgrading your typescript dependency. In the cloudevents module, we are using 3.8.3 and with that version `tsc` does not suffer from these problems.

**Comment by grant** [comment]
Merge with master should pull the latest TS version now.

**Comment by grant** [comment]
I think there needs to be some work with fixing the invoker for the current CE implementation before adding this module.

I've been getting into feature-creep trying to fix too many things at once. So I'll close this PR and we should continue with a smaller PR.

**Pull request closed without merging**
