### PR TITLE
Inline Dockerfile and gcloud commands.

### PR DESCRIPTION
**Pull request by josephburnett**
Add Dockerfile and gcloud commands to README.

It isn't clear how to deploy the same function to all three environments, Cloud Functions, Cloud Run and Cloud Run on GKE.  What's missing is a Dockerfile and example gcloud commands.  There are links to the relevant quickstarts, but it made me think I was in the wrong place.

### CODE REVIEW

**Comment by grant** [comment]
@josephburnett Thanks for the PR, this is very useful.
However, can you open an issue first? There are some questions we should ask first.

For example, I think this `Dockerfile` should live in an `examples/` folder or somewhere besides the `README.md`.

In addition, I don't think we want to tie the functions framework to `gcloud` or runtimes like `nodejs8`. These commands will change with time and we should be careful about maintaining them.

**Comment by stew-r** [comment]
+1 to grant's comment. IMO this belongs in a Medium/blog post rather than as content that we own and maintain. What if we posted this elsewhere and just linked to it from the repo (e.g., "here's a collection of great links that show you how to do things with the Functions Framework")?

**Comment by josephburnett** [comment]
@stew-r @swalkowski, could you take a look at this change?

I used the functions framework in a demo for a customer recently.  I knew FF was what I wanted, but I was tripped up by references to other getting-started guides.

**Comment by AndreiIgna** [comment]
All this info is really useful, maybe can be added as Wiki pages here on GitHub so it's easier to find.

A few important things about using the functions framework were quite tricky to do, and found the info in closed issues..

**Comment by grant** [comment]
@AndreiIgna Please link or re-open the issues if you think we should add them in docs.

**Comment by stew-r** [comment]
@grant should we move [your PR](https://github.com/GoogleCloudPlatform/functions-framework-nodejs/pull/46) forward and make that a location for specialized and community docs contributions?

**Comment by grant** [comment]
@stew-r Up to you. I think critical docs should be part of the repo, like how to configure a Dockerfile to use this module, should be in this repo rather than our [community docs](https://github.com/GoogleCloudPlatform/community).

For example in `@google/clasp`, the `docs/` folder is useful for advanced features not meant in the README and is maintained by the community.
https://github.com/google/clasp/tree/master/docs

**Comment by grant** [comment]
@josephburnett Could you move the contents of this PR into the new `docs/` folder? That'd be awesome.

**Comment by grant** [comment]
@josephburnett Do you want to make the changes (move to `docs/`) or should I go ahead and make the doc change and close this PR?

**Comment by grant** [comment]
FYI, I've created a PR that moves this change to the `docs/` directory.

**Pull request closed without merging**
