### PR TITLE
Update README

### PR DESCRIPTION
**Pull request by steren**
- Cloud Run on GKE -> Cloud Run for Anthos
- use source deploy instead of Dockerfile

### CODE REVIEW

**Review by grant — APPROVED** [review]
Thank you.

**Comment by steren** [comment]
Does GitHub UI allows me to amend a commit? If not, then it's too much friction to use the git CLI just to edit a title

**Comment by grant** [comment]
> Does GitHub UI allows me to amend a commit? If not, then it's too much friction to use the git CLI just to edit a title

The GitHub UI allows you to add a commit message when creating the commit. There is GitHub Desktop and other tools besides the git cli.

You can also just make a minor change and make sure add `docs: ` in the commit message.

Sorry, I can't merge a commit that doesn't pass CI. These commits are used in release notes and other tools across Cloud.

**Comment by steren** [comment]
https://github.com/GoogleCloudPlatform/functions-framework-nodejs/pull/320

**Pull request closed without merging**
