### PR TITLE
Add cookieParser middleware

### PR DESCRIPTION
**Pull request by Tebro**
You can already set cookies, but they are not parsed into the Request without this middleware.

### CODE REVIEW

**Comment by grant** [comment]
Huy, what do you think?
This cookie parsing middleware is quite common in Express applications.
It's 1 dependency, 94kb, shouldn't be a huge impact on GCF.

**Comment by squee1945** [comment]
What is the use case for a function to read cookies?

**Comment by Tebro** [comment]
My current use case is for a OICD flow for my Slack application. (To couple slack users to O365 users).

Need to persist some user information in some kind of session and cookies was a convenient way to do that.

**Comment by squee1945** [comment]
The HTTP headers are available. Can you use a cookie package against the header directly? I.e., why does it need to be middleware?

**Comment by grant** [comment]
I'd guess you'd be able add the Express middleware like you can do with the Express Routing middleware:

I have a blogpost on how to add middleware. Here are some useful links:
- https://medium.com/google-cloud/express-routing-with-google-cloud-functions-36fb55885c68
- https://github.com/expressjs/cookie-parser#api

**Comment by Tebro** [comment]
Hmm, that would probably work as well if the functions framework wants leave this out.

**Comment by grant** [comment]
Yeah, the FF is not including anything that is not essential, including Express' cookie parsing middleware. The FF really should only include essential features that can be implemented in all languages very easily. For example, if some GCF developers don't want this feature, we shouldn't force them to use it and increase their module size.

**Comment by grant** [comment]
I'll look into writing a blogpost about Cookie parsing with the FF.

**Comment by grant** [comment]
We're going to let users parse cookies from the `request` object, and not add this Express middleware.

**Pull request closed without merging**
